# This is Makefile for ESP32 IDF

COMPONENT_ADD_INCLUDEDIRS := ./gme
COMPONENT_SRCDIRS := ./gme
CPPFLAGS += -DUSE_GME_VGM -DVGM_YM2612_GENS
# -DVGM_YM2612_GENS -DUSE_GME_AY

# COMPONENT_DEPENDS := spibus
