# This is Makefile for ESP32 IDF

COMPONENT_ADD_INCLUDEDIRS := ./include
COMPONENT_SRCDIRS := ./src ./src/chips
CPPFLAGS += -DVGM_RTOS -DVGM_NO_ZLIB -DDISABLE_HW_SUPPORT -DVGM_LITTLE_ENDIAN -DENABLE_ALL_CORES
CPPFLAGS += -DVGM_AY8910 -DVGM_TEST

# COMPONENT_DEPENDS := spibus
